### ISSUE TITLE
unfavorable tmp path in method generatePdfContent()

### ISSUE THREAD

**Issue by ebolansk** [Conspir3D/typo3-janolawservice#1]
maybe just a typo but the absolute path `/typo3temp/` is in some hosting environments by open_basedir directove.
Is it possible to use the TYPO3 internal `./typo3temp/` directory?

**Comment by ebolansk** [comment]
https://github.com/Conspir3D/typo3-janolawservice/blob/master/Classes/Utility/JanolawConfigurationUtility.php#L173

**Comment by VeraSpiegel** [comment]
Thank you very much for the fix. I have commited it to our base repository und merged your pull request. 
Can we close the ticket?
