### ISSUE TITLE
Exception thrown while opening the extension configuration in install tool

### ISSUE THREAD

**Issue by rteitge** [Conspir3D/typo3-janolawservice#6]
Hi,

there is an exception thrown everytime I try to open the extension configuration in install tool:
```
Core: Exception handler (WEB): Uncaught TYPO3 Exception: Call to a member function request() on null
Error thrown in file /html/typo3-composer/public/typo3conf/ext/janolawservice/Classes/Utility/JanolawConfigurationUtility.php in line 64
Requested URL: https://www.domain.xyz/typo3/install.php?install[controller]=settings&install[context]=backend&install[action]=extensionConfigurationGetContent
```

Best regards

Environment:
janolawservice 3.0.2
TYPO3 11.5.30
PHP 8.1.13

**Comment by VeraSpiegel** [comment]
Hi @rteitge,
I have fixed this. There was a problem with injection when using a user function in ext_conf_template.txt. 
I am not sure if this is connected with the latest TYPO3 Updates, but it is fixed now.
Thank you for your feedback!
Vera

**Comment by VeraSpiegel** [comment]
Fine, i close the ticket.
