### ISSUE TITLE
Exception thrown while opening extension configuration in install tool

### ISSUE THREAD

**Issue by rteitge** [Conspir3D/typo3-janolawservice#7]
Hi there,

I moved to TYPO3 v12 and got an exception at opening the extension configuration in install tool.

```
Core: Exception handler (WEB): Uncaught TYPO3 Exception: 
Too few arguments to function TYPO3\CMS\Core\Http\RequestFactory::__construct(), 0 passed
in .../typo3conf/ext/janolawservice/Classes/Utility/JanolawConfigurationUtility.php on line 45 and exactly 1 expected 
```

Imho the RequestFactory should be injected by constructor like there: [HTTP requests to external sources](https://docs.typo3.org/m/typo3/reference-coreapi/11.5/en-us/ExtensionArchitecture/HowTo/RestRequests/Index.html#basic-usage)

Environment:
janolawservice 3.0.3
TYPO3 12.4.5
PHP 8.1.21

Best regards

**Comment by VeraSpiegel** [comment]
Hi @rteitge,
i have made some refactoring, it works now for me, new Version of the extension is 3.0.4.
Thank you for your feedback!
Vera

**Comment by rteitge** [comment]
Hi @VeraSpiegel,

I can confirm that it works now, thank you very much!
Roman
